### ISSUE TITLE
Feature Request: Option to remove "fast core bars"

### ISSUE THREAD

**Issue by hmijail** [mikepj/XRG#14]
Showing the CPU graph nearly doubles the CPU usage of XRG in my configuration. I suspect this is because of the fast per-core bars; the Fast CPU Bar is already disabled.

It'd be great to have an option to either disable the fast core bars or have them honor the graph update frequency setting.

Thank you for XRG!

**Comment by mikepj** [comment]
Thanks for the feedback.  I removed the traditional "Fast CPU" bar because it feels obsolete with the new individual CPU bars shown in the latest release.  Instead that Preference will now toggle whether the individual CPU bars are shown.

This change was made in the following commit:  f1bd87645ede305c3198a8eb4ef0f15d38b2dcf2

Should be present in XRG 3.1.
