### ISSUE TITLE
(CPU/GPU) temperature sensors having cryptic names and not selectable for graph

### ISSUE THREAD

**Issue by germanicianus** [mikepj/XRG#17]
See subject and below screenshot.
System: MacBook Air M1 8 core GPU, macOS Big Sur 11.3, XRG 3.0
![Bild 02 05 21 um 16 37](https://user-images.githubusercontent.com/37223176/116817347-29b9fa00-ab66-11eb-940c-8725f37870c3.jpg)
I also encounter issue #12 - quite funny that the temperature sensors are recognized:
![Bild 02 05 21 um 16 51](https://user-images.githubusercontent.com/37223176/116817589-69cdac80-ab67-11eb-865c-189e55f003ca.jpg)

**Comment by mikepj** [comment]
Fixed in XRG 3.1 with a new checkbox in the Temperature Graph Preferences to enable/disable unknown sensors.  Unknown sensors are now selectable as well.  You might need to close and reopen the Preferences window before an unknown sensor is selectable.  Also note that keeping track of unknown sensors takes a higher CPU load.
<img width="612" alt="Screen Shot 2022-01-16 at 10 41 53 PM" src="https://user-images.githubusercontent.com/831229/149704754-f535cf00-7503-4a07-b540-8f7ca5ad6971.png">

**Comment by kolmar-kafran** [comment]
There are so many sensors. Which one should I use to just track the CPU temperature on an M1 Mac?
